# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-21 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TruckMember',
            new_name='TruckFollower',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='members',
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_follower',
            field=models.ManyToManyField(through='trucks.TruckFollower', to=settings.AUTH_USER_MODEL),
        ),
    ]
